BLEND-181: Improve installing render delegate
bnagirniak/blender pull request #30
Opened 2022-08-03 20:56 UTC by VascoPi

Improved Addon properties UI.
Added Delegate directory settings.
Made delegate list dynamic.

2022-08-04 12:36 UTC, bnagirniak requested changes

2022-08-04 12:36 UTC, bnagirniak commented on extern/usdhydra/addon/properties/preferences.py
> +        items=(('SETTINGS', "Settings", "aaa"),
fix "aaa"

2022-08-04 12:36 UTC, bnagirniak commented on extern/usdhydra/addon/utils/delegate.py
> +        exit()
better: `from .. import engine`

2022-08-04 12:36 UTC, bnagirniak commented on extern/usdhydra/python.cpp
>    }
remove this

2022-08-04 12:36 UTC, bnagirniak commented on extern/usdhydra/addon/properties/preferences.py
> +            plugins = Plug.Registry().GetAllPlugins()
remove this

2022-08-05 15:37 UTC, DagerD approved these changes

2022-08-05 15:45 UTC, bnagirniak approved these changes

2022-08-05 15:45 UTC, merged